Repository grafana/grafana-plugin-repository, pull requests merged in 2018-11, with the labels that each got.

#337 Instana datasource plugin 1.3.0
  repo.json
Labels: plugin_update

#338 add grafana-polystat-panel
  repo.json
Labels: new_plugin, pr_action: changes needed

#334 Add new panel: larona-epict-panel
  repo.json
Labels: new_plugin

#336 Update akumuli-datasource
  repo.json
Labels: plugin_update, pr_action: changes needed

#339 Instana datasource plugin 1.3.1
  repo.json
Labels: plugin_update
