Repository grafana/grafana-plugin-repository, pull requests merged in 2018-12, with the labels that each got.

#341 flant-statusmap-panel v0.0.3
  repo.json
Labels: plugin_update

#320 Add enhanced JSON datasource
  repo.json
Labels: new_plugin

#342 Instana datasource plugin 2.0.0
  repo.json
Labels: plugin_update, pr_action: feedback from author needed

#340 Added grafana_status_panel version 1.0.9
  repo.json
Labels: plugin_update, pr_action: changes needed

#348 update kentik-app to v1.3.2
  repo.json
Labels: plugin_update

#343 Update flant-statusmap-panel version to 0.0.4
  repo.json
Labels: plugin_update

#345 Update JSON datasource to v0.1.1
  repo.json
Labels: plugin_update

#346 Update larona-epict-panel to 1.0.1
  repo.json
Labels: plugin_update

#351 update discrete to 0.0.9
  repo.json
Labels: plugin_update
