Repository grafana/grafana-plugin-repository, pull requests merged in 2019-05, with the labels that each got.

#415 0.2.5 uppdate flowcharting panel
  repo.json
Labels: plugin_type: panel, plugin_update

#416 Update Multistat to version 1.2.2 with bug fix to correct group/value sorting bug
  repo.json
Labels: plugin_type: panel, plugin_update

#423 Updated larona-epict-panel to version 1.2.1
  repo.json
Labels: plugin_type: panel, plugin_update

#418 Radar Panel v1.4.4 (20/Apr/2019)
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: feedback from author needed

#425 Added Theme Panel
  repo.json
Labels: new_plugin, plugin_type: panel

#419 Update Annunciator to version 1.0.2 with bug fix needed for Grafana 6.1+
  repo.json
Labels: plugin_type: panel, plugin_update

#385 opennms-helm plugin v3.0.1
  repo.json
Labels: plugin_type: app, plugin_update

#429 Instana datasource plugin 2.2.4
  repo.json
Labels: plugin_update

#434 update kentik app
  repo.json
Labels: plugin_update
