Repository grafana/grafana-plugin-repository, pull requests merged in 2019-10, with the labels that each got.

#490 Instana datasource plugin 2.4.1
  repo.json
Labels: commercial plugin, plugin_update

#466 Add rockset datasource plugin
  repo.json
Labels: new_plugin, plugin_type: datasource

#494 Update parity report panel to v1.2.1
  repo.json
Labels: plugin_type: panel, plugin_update

#495 Update Breadcrumb plugin
  repo.json
Labels: plugin_type: panel, plugin_update

#474 Update akumuli-datasource plugin to 1.3.9
  repo.json
Labels: plugin_type: datasource, plugin_update, pr_action: changes needed

#491 Multistat update to 1.2.4 - fix for grafana 6.4.x table data response error.
  repo.json
Labels: plugin_type: panel, plugin_update

#489 Update devopsprodigy-kubegraf-app to 1.1.1
  repo.json
Labels: plugin_type: app, plugin_update

#481 radensolutions-netxms-datasource updated to version 1.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#499 Update Flowcharting 0.5.0
  repo.json
Labels: plugin_type: panel, plugin_update
