Repository grafana/grafana-plugin-repository, pull requests merged in 2019-06, with the labels that each got.

#431 bump Skydive datasource version
  repo.json
Labels: plugin_update, pr_action: changes needed

#426 Update Flowcharting panel 0.3.0
  repo.json
Labels: plugin_update

#441 Update corpglory-progresslist-panel to 1.0.4
  repo.json
Labels: plugin_type: panel, plugin_update

#440 Instana datasource plugin 2.3.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#438 upgrade `goshposh-metaqueries-datasource` to `0.0.2`
  repo.json
Labels: plugin_type: datasource, plugin_update

#445 Update ImageIt to v0.1.1
  repo.json
Labels: plugin_type: panel, plugin_update

#446 Added linksmart-hds-datasource v1.0.0
  repo.json
Labels: plugin_type: datasource, plugin_update
