Repository grafana/grafana-plugin-repository, pull requests merged in 2019-04, with the labels that each got.

#407 Update larona-epict-panel
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#403 Add pierosavi-imageit-panel to repo.json
  repo.json
Labels: new_plugin, plugin_type: panel

#420 zabbix plugin v3.10.2
  repo.json
Labels: plugin_type: app, plugin_update

#424 update worldping to 1.2.6
  repo.json
Labels: plugin_type: app, plugin_update
