Repository grafana/grafana-plugin-repository, pull requests merged in 2019-03, with the labels that each got.

#381 Add minor new version (1.2.0) of multistat
  repo.json
Labels: plugin_update, pr_action: feedback from author needed

#383 Update JSON datasource to v0.1.2
  repo.json
Labels: plugin_type: datasource, plugin_update, pr_action: changes needed

#382 thruk-datasource: update to 1.0.3
  repo.json
Labels: plugin_update, pr_action: feedback from author needed

#391 Cloudflare Grafana App version 0.1.4
  repo.json
Labels: plugin_type: app, plugin_update

#390 Update linksmart-sensorthings-datasource to v1.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#386 Update fetzerch-sunandmoon-datasource plugin (v0.1.3)
  repo.json
Labels: plugin_type: datasource, plugin_update

#356 Blendstat panel
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#313 updating ambari metrics datasource to v1.2.0
  repo.json
Labels: plugin_update, pr_action: changes needed

#294 Add new panel: gretamosa-topology-panel
  repo.json
Labels: new_plugin, plugin_type: panel

#280 Adding Pagerduty datasource
  repo.json
Labels: new_plugin, plugin_type: datasource

#182 add grafana-progress-list-plugin
  repo.json
Labels: pr_action: changes needed

#364 Add 'pr0ps-trackmap-panel' plugin
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#396 Update flant-statusmap-panel version to 0.1.0
  repo.json
Labels: plugin_type: panel, plugin_update

#392 Update 'pr0ps-trackmap-panel' to v2.0.4
  repo.json
Labels: plugin_type: panel, plugin_update

#393 Update fetzerch-sunandmoon-datasource plugin (v0.1.4)
  repo.json
Labels: plugin_type: datasource, plugin_update

#401 New panel plugin Flowcharting
  repo.json
Labels: new_plugin, plugin_type: panel

#404 Update Breadcrumb panel
  repo.json
Labels: plugin_type: panel, plugin_update
