Repository grafana/grafana-plugin-repository, pull requests merged in 2019-08, with the labels that each got.

#459 Update Version to 0.1.2
  repo.json
Labels: plugin_type: datasource, plugin_update

#460 Update fetzerch-sunandmoon-datasource plugin (v0.1.5)
  repo.json
Labels: plugin_type: datasource, plugin_update

#463 Zabbix plugin v3.10.4
  repo.json
Labels: plugin_type: app, plugin_update

#470 upgrade `goshposh-metaqueries-datasource` to `0.0.3`
  repo.json
Labels: plugin_update
