Repository grafana/grafana-plugin-repository, pull requests merged in 2019-01, with the labels that each got.

#353 Update marcuscalidus-svg-panel V0.3.0
  repo.json
Labels: plugin_update, pr_action: changes needed

#355 Update peak-report plugin to 0.2.4
  repo.json
Labels: plugin_update

#357 grafana-thruk-datasource: add 1.0.2 release
  repo.json
Labels: plugin_update

#317 Update repo.json to add scadavis-synoptic-panel
  repo.json
Labels: new_plugin

#358 Instana datasource plugin 2.1.0
  repo.json
Labels: plugin_update

#363 grafana-polystat-panel: release version 1.0.15
  repo.json
Labels: plugin_update
