Repository grafana/grafana-plugin-repository, pull requests merged in 2019-02, with the labels that each got.

#323 Added Diagram v1.4.5
  repo.json
Labels: plugin_update, pr_action: changes needed

#374 piechart-panel release v1.3.5
  repo.json
Labels: bug

#370 release kentik-app v1.3.3
  repo.json
Labels: plugin_update

#376 update piechart-panel to 1.3.6
  repo.json
Labels: plugin_update

#352 Update repo.json adding the details for michaeldmoore-multistat-panel
  repo.json
Labels: new_plugin

#367 Update larona-epict-panel
  repo.json
Labels: plugin_update

#368 update snuids/grafana-radar-panel v1.4.2
  repo.json
Labels: plugin_update

#378 Release Plotly panel 0.0.6
  repo.json
Labels: plugin_update

#372 Update gridprotectionalliance-osisoftpi-datasource to version 1.0.4
  repo.json
Labels: plugin_update

#375 Update clickhouse-grafana to 1.8.1
  repo.json
Labels: plugin_update

#365 Release prometheus-alertmanager-datasource 0.0.7
  repo.json
Labels: plugin_update

#379 Release ajax 0.0.6
  repo.json
Labels: plugin_update

#387 yesoreyeram-boomtable-panel v1.0.0
  repo.json
Labels: plugin_type: panel, plugin_update
