Repository grafana/grafana-plugin-repository, pull requests merged in 2019-09, with the labels that each got.

#468 Add devopsprodigy-kubegraf app v1.0.0
  repo.json
Labels: new_plugin, plugin_type: app

#487 updated Alexandra-track-map to v.1.2.0
  repo.json
Labels: plugin_type: panel, plugin_update

#483 Update devopsprodigy-kubegraf-app to 1.1.0
  repo.json
Labels: plugin_type: app, plugin_update

#488 Update Flowcharting [0.4.0] - 2019-09-26
  repo.json
Labels: new_plugin, plugin_type: panel
