Repository grafana/grafana-plugin-repository, pull requests merged in 2019-07, with the labels that each got.

#452 BigQuery Datasource Version 1.0.1
  repo.json
Labels: plugin_type: datasource, plugin_update

#451 Boom Table panel - v1.3.0
  repo.json
Labels: plugin_type: panel, plugin_update

#453 zabbix plugin v3.10.3
  repo.json
Labels: plugin_type: app, plugin_update

#448 Updated Diagram panel for Grafana v5.x and initial support for v6.x
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#447 Add kapacitor-grafana-datasource in repo.json
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed

#442 Add QuasarDB Grafana Datasource Plugin
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed
