Repository grafana/grafana-plugin-repository, pull requests merged in 2019-12, with the labels that each got.

#507 Add percent plus panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#535 Update akumuli-datasource to 1.3.10
  repo.json
Labels: plugin_type: datasource, plugin_update

#522 OpenNMS Helm 4.0.2
  repo.json
Labels: plugin_type: app, plugin_update

#523 Add macropower-analytics-panel
  repo.json
Labels: new_plugin, plugin_type: panel

#525 marcuscalidus-svg-panel Version 0.3.3 added
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#528 Update Organisations panel to support Grafana 6
  repo.json
Labels: plugin_type: panel, plugin_update

#529 Updated Alexandra-trackmap-panel to version 1.2.3
  repo.json
Labels: plugin_type: panel, plugin_update

#530 QuasarDB Datasource plugin version update to 3.5.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#520 Update DevOpsProdigy KubeGraf App version to v1.2.0
  repo.json
Labels: plugin_type: app, plugin_update, pr_action: changes needed

#533 Update flowcharting 0.6.0
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#537 add offical spotify heroic datasource plugin.
  repo.json
Labels: plugin_type: datasource, pr_action: changes needed

#539 Instana datasource plugin 2.5.0
  repo.json
Labels: plugin_type: datasource, plugin_update
