Repository grafana/grafana-plugin-repository, pull requests merged in 2019-11, with the labels that each got.

#512 Update Blendstat panel to 1.0.2
  repo.json
Labels: plugin_type: panel, plugin_update

#503 Update Multistat to version 1.2.5 (Adding Line/Curve optional feature)
  repo.json
Labels: plugin_type: panel, plugin_update

#513 Instana datasource plugin 2.4.4
  repo.json
Labels: plugin_type: datasource, plugin_update

#510 Update OpenNMS Helm Plugin to 4.0.1
  repo.json
Labels: plugin_type: datasource, plugin_update

#518 Release v0.1.5 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#514 BIGQuery Data source ver 1.0.3
  repo.json
Labels: plugin_type: datasource, plugin_update, pr_action: changes needed
