Repository grafana/grafana-plugin-repository, pull requests merged in 2020-09, with the labels that each got.

#706 Added ACE.SVG
  repo.json
Labels: new_plugin, plugin_type: panel

#722 Zabbix plugin v4.0.1
  repo.json
Labels: plugin_type: app, plugin_update

#721 Update Static data source to v0.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#712 Sunburst plugin for Grafana
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#724 Add Static data source v0.4.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#728 Update Static data source to v1.0.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#665 update sni-thruk-datasource to 1.0.4
  repo.json
Labels: angular, plugin_type: datasource, plugin_update, pr_action: changes needed

#666 update sni-pnp-datasource to 1.0.6
  repo.json
Labels: angular, plugin_type: datasource, plugin_update, pr_action: changes needed

#725 Added grafana_status_panel version 1.0.10
  repo.json
Labels: plugin_type: panel, plugin_update

#743 Add JSON API data source
  repo.json
Labels: new_plugin, plugin_type: datasource

#744 Add JSON API data source v0.3.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#745 Update versions for marcusolsson plugins
  repo.json
Labels: plugin_type: datasource, plugin_type: panel, plugin_update

#747 Add JSON API v0.4.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#714 Publish dalvany-image-panel version 2.2.0
  repo.json
Labels: plugin_type: panel, plugin_update
