Repository grafana/grafana-plugin-repository, pull requests merged in 2020-10, with the labels that each got.

#739 Included video panel
  repo.json
Labels: new_plugin, plugin_type: panel

#736 Updated gridprotectionalliance-osisoftpi-datasource to version 1.1.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#748 Update video panel - Include predefined value for YouTube ID
  repo.json
Labels: plugin_type: panel, plugin_update

#757 Update flant-statusmap-panel version to 0.3.4
  repo.json
Labels: plugin_type: panel, plugin_update

#717 Add Timepicker Buttons Panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel

#735 initial release Pareto chart plugin
  repo.json
Labels: new_plugin, plugin_type: panel

#738 plugin: diagram - adds v1.6.4 and v1.7.1
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#776 fix: update linter for new url-based publishing
  .vscode/launch.json
  repo.json
  scripts/github/github.js
  scripts/lint-plugin.js
  scripts/lint-repo.js
  scripts/lintPlugin.js
  scripts/lintRepoUpdate.js
Labels: enhancement, plugin_type: panel, plugin_update
