Repository grafana/grafana-plugin-repository, pull requests merged in 2020-12, with the labels that each got.

#805 Add Hexmap panel
  repo.json
Labels: new_plugin, plugin_type: panel

#806 Update JSON API v0.7.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#808 Update hourly-heatmap v0.9.0
  repo.json
Labels: plugin_type: panel, plugin_update

#809 Update JSON API data source v0.7.1
  repo.json
Labels: plugin_type: datasource, plugin_update

#783 Add Humio-datasource plugin
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed

#764 add Flowhook 0.1.2
  repo.json
Labels: new_plugin, plugin_type: datasource

#801 Update fetzerch-sunandmoon-datasource plugin (v0.2.1)
  repo.json
Labels: plugin_type: datasource, plugin_update

#731 Gapit htmlgraphics panel
  repo.json
Labels: new_plugin, plugin_type: panel

#810 Update Treemap panel v0.7.0
  repo.json
Labels: plugin_type: panel, plugin_update
