Repository grafana/grafana-plugin-repository, pull requests merged in 2020-11, with the labels that each got.

#770 Update marcusolsson plugins
  repo.json
Labels: plugin_type: datasource, plugin_type: panel, plugin_update

#788 Update JSON API v0.6.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#790 Update Treemap panel v0.6.0
  repo.json
Labels: plugin_type: panel, plugin_update

#792 Update JSON API v0.6.1
  repo.json
Labels: plugin_type: datasource, plugin_update, signed

#784 Update Consul datasource plugin to v0.2.1
  repo.json
Labels: plugin_type: datasource, plugin_update, signed

#791 cognite datasource v2.1.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#794 riemann datasource plugin 0.1.3
  repo.json
Labels: new_plugin, plugin_type: datasource, signed

#789 Update fetzerch-sunandmoon-datasource plugin (v0.2.0)
  repo.json
Labels: plugin_type: datasource, plugin_update, signed

#756 Updating cloudspout-button-panel to version 7.0.23
  repo.json
Labels: plugin_type: panel, plugin_update

#800 Update marcusolsson plugins
  repo.json
Labels: plugin_type: datasource, plugin_update

#802 Add CSV data source v0.1.0
  repo.json
Labels: new_plugin, plugin_type: datasource
