Repository grafana/grafana-plugin-repository, pull requests merged in 2020-06, with the labels that each got.

#596 radensolutions-netxms-datasource updated to version 1.2.2
  repo.json
Labels: plugin_update, pr_action: feedback from author needed

#638 Update flowcharting 0.9.0
  repo.json
Labels: plugin_type: panel, plugin_update

#639 Hourly heatmap panel v0.3.2
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#630 Update Multistat to v1.4.0 (restyled tooltips plus clickable bar-links for drilldowns)
  repo.json
Labels: plugin_update

#655 Update macropower-analytics-panel (v1.0.0)
  repo.json
Labels: plugin_type: panel, plugin_update

#640 Bump version 1.0.8
  repo.json
Labels: angular, plugin_type: datasource, plugin_update, pr_action: changes needed

#642 Update 'pr0ps-trackmap-panel' to v2.1.0
  repo.json
Labels: angular, plugin_type: panel, plugin_update

#599 Update repo.json
  repo.json
Labels: angular, plugin_type: datasource, plugin_update, pr_action: changes needed

#659 Add treemap panel
  repo.json
Labels: new_plugin, plugin_type: panel, react

#657 chore(warp10): update plugin to 2.2.0
  repo.json
Labels: angular, plugin_type: datasource, plugin_update

#633 Release v3.6.0 .. v3.8.2 quasardb-datasource
  repo.json
Labels: angular, plugin_type: datasource, plugin_update

#661 Update DevOpsProdigy KubeGraf App version to v1.4.1
  repo.json
Labels: angular, plugin_type: app, plugin_update

#644 Adding word cloud panel
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed, react

#628 Add an image panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel, react

#658 Add cloudspout-button-panel
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed, react
