Repository grafana/grafana-plugin-repository, pull requests merged in 2020-07, with the labels that each got.

#664 release cognite-datasource v2.0.0
  repo.json
Labels: angular, plugin_type: datasource, plugin_update

#656 Clickhouse Datasource plugin version update to 2.0.1
  repo.json
Labels: angular, plugin_type: datasource, plugin_update

#671 Clickhouse Datasource plugin version update to 2.0.2
  repo.json
Labels: plugin_update

#691 Add grafana-hourly-heatmap-panel-0.4.0
  repo.json
Labels: plugin_type: panel, plugin_update, react

#692 Add grafana-treemap-panel-0.2.0
  repo.json
Labels: plugin_type: panel, plugin_update, react
