Repository grafana/grafana-plugin-repository, pull requests merged in 2020-01, with the labels that each got.

#545 Strava datasource v1.0.0
  repo.json
Labels: new_plugin, plugin_type: datasource

#550 Clickhouse Datasource plugin version update to 1.9.5
  repo.json
Labels: plugin_type: datasource, plugin_update

#541 Update akumuli-datasource to 1.3.11
  repo.json
Labels: plugin_type: datasource, plugin_update

#544 update imageit to 0.1.3
  repo.json
Labels: plugin_type: panel, plugin_update

#551 Release v0.1.7 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#554 BQ DataSource 1.0.5
  repo.json
Labels: plugin_update

#559 Release ovh-warp10-datasource v2.1.2
  repo.json
Labels: plugin_update
