Repository grafana/grafana-plugin-repository, pull requests merged in 2020-05, with the labels that each got.

#615 Update Flowcharting 0.8.0
  repo.json
Labels: plugin_type: panel, plugin_update

#598 Update Annunciator to v1.0.5, adding new 'Shock & Awe' alarm indicator
  repo.json
Labels: plugin_update, pr_action: changes needed

#610 Updated Alexandra-trackmap-panel to version 1.2.5
  repo.json
Labels: plugin_type: panel, plugin_update

#626 Release v0.2.0 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#631 Update fetzerch-sunandmoon-datasource plugin (v0.1.6)
  repo.json
Labels: plugin_update

#620 Update DevOpsProdigy KubeGraf App version to v1.4.0
  repo.json
Labels: plugin_update
