Repository grafana/grafana-plugin-repository, pull requests merged in 2020-08, with the labels that each got.

#698 Static data source v0.1.0
  repo.json
Labels: new_plugin, plugin_type: datasource, react

#689 Add Finnhub datasource plugin
  repo.json
Labels: new_plugin, plugin_type: datasource, react

#645 New version of bubble chart
  repo.json
Labels: angular, plugin_type: panel, plugin_update, pr_action: changes needed

#702 Add Hourly heatmap v0.5.0
  repo.json
Labels: plugin_type: panel, plugin_update

#635 grafana-button-panel v0.1.0
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed, react

#688 Update cloudspout-button-panel to version 7.0.4
  repo.json
Labels: plugin_type: panel, plugin_update

#699 Update macropower-analytics-panel (v1.1.1)
  repo.json
Labels: plugin_type: panel, plugin_update

#611 Add Matomo Tracker panel
  repo.json
Labels: commercial plugin, plugin_type: panel, pr_action: changes needed, react

#697 Update to version 1.1.3
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#593 Add Untimely panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed, react

#690 Clickhouse Datasource plugin version update to 2.1.0
  repo.json
Labels: plugin_type: datasource, plugin_update, pr_action: changes needed

#667 Boom Table v1.4
  repo.json
Labels: angular, plugin_type: panel, plugin_update, pr_action: changes needed

#687 Release v0.2.1 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#686 Update Multistat to 1.4.1 to fix bug with Grafana 7.1
  repo.json
Labels: plugin_type: panel, plugin_update

#680 Update flant-statusmap-panel version to 0.3.1
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#602 Add GraphQL datasource
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed, react

#705 Instana datasource plugin 3.0.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#675 Add traceroute-map-panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#678 Add chaos mesh datasource
  repo.json
Labels: new_plugin, plugin_type: datasource

#715 Add Dynamic text panel v1.0.0
  repo.json
Labels: new_plugin, plugin_type: panel

#654 Service Dependency Graph v2.3.0
  repo.json
Labels: angular, new_plugin, plugin_type: panel, pr_action: changes needed

#711 Release Cognite data source v2.0.1
  repo.json
Labels: plugin_type: datasource, plugin_update
