Repository grafana/grafana-plugin-repository, pull requests merged in 2020-03, with the labels that each got.

#579 Update Multistat version to 1.2.6
  repo.json
Labels: plugin_update

#572 HDS Datasource plugin v1.0.1
  repo.json
Labels: plugin_update, pr_action: changes needed

#578 Update Darksky Datasource
  repo.json
Labels: plugin_update, pr_action: changes needed

#560 Updated Alexandra-Trackmap-Panel to version 1.2.4
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: feedback from author needed

#543 Add aidanmountford-html-panel
  repo.json
Labels: new_plugin, plugin_type: panel
