Repository grafana/grafana-plugin-repository, pull requests merged in 2021-05, with the labels that each got.

#908 Update frser-sqlite-datasource to v1.0.3 / v1.1.0 / v1.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#917 Update gapit-htmlgraphics-panel v1.3.3
  repo.json
Labels: plugin_type: panel, plugin_update

#915 Update imageit to 1.0.3
  repo.json
Labels: plugin_type: panel, plugin_update

#887 Add Infinity datasource - v0.6.0
  repo.json
Labels: new_plugin, plugin_type: datasource

#916 Update larona-epict-panel to v2.0.3
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: feedback from author needed

#862 Apache Cassandra Datasource
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed

#936 Add anodot-datasource v. 1.0.1 and anodot-panel v 1.0.1
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_type: panel, plugin_update

#932 Add Redis Explorer plug-in
  repo.json
Labels: commercial plugin, new_plugin, plugin_type: datasource

#946 Update Redis Application plug-in 1.2.0
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#904 bmchelix ade datasource v21.02
  repo.json
Labels: commercial plugin, new_plugin, plugin_type: datasource, pr_action: changes needed

#796 update discrete panel
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#795 update ajax plugin t 0.1.0
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#957 Cognite data source v2.3.0
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#958 Publishing V1.0.1
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update
