Repository grafana/grafana-plugin-repository, pull requests merged in 2021-08, with the labels that each got.

#1009 Add vertica-grafana-datasource plugin
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, signature/commercial, submission/new, type/datasource

#906 Updated flaminggoat-maptrack3d-panel to v0.1.9
  repo.json
Labels: submission/update, type/panel

#954 Update thalysantana-appcenter-datasource v1.0.1
  repo.json
Labels: milestone/needs-review, submission/update, type/datasource

#1022 Anodot - minor readme updates
  repo.json
Labels: milestone/needs-changes, submission/update, type/datasource, type/panel

#956 Publish v1.0.0 of itrs-hub-datasource
  repo.json
Labels: milestone/needs-changes, milestone/needs-feedback, signature/commercial, submission/new, type/datasource

#1015 Update imageit-panel to 1.0.5
  repo.json
Labels: type/panel, submission/update

#1018 Instana datasource plugin 3.3.1
  repo.json
Labels: signature/commercial, type/datasource, submission/update

#1040 Release Cognite Data Source v2.4.0
  repo.json
Labels: signature/commercial, type/datasource, milestone/needs-review, submission/update

#1042 Anodot panel 1.0.5
  repo.json
Labels: signature/commercial, type/panel, milestone/needs-review, submission/update

#1047 Update tencentcloud-monitor-app to 2.2.2
  repo.json
Labels: signature/commercial, type/app, milestone/needs-review, submission/update
