Repository grafana/grafana-plugin-repository, pull requests merged in 2021-03, with the labels that each got.

#824 Add v0.2.0 of the Untimely Factry panel
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: feedback from author needed

#827 added grafana-meta-queries version 0.0.4
  repo.json
Labels: plugin_type: datasource, plugin_update, pr_action: feedback from author needed

#888 Instana datasource plugin 3.2.0
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#870 Update sskgo-perfcurve-panel to v1.4.0
  repo.json
Labels: plugin_type: panel, plugin_update

#874 Update flant-statusmap-panel version to 0.4.1
  repo.json
Labels: plugin_type: panel, plugin_update

#882 Updated larona-epict-panel to v2.0.1
  repo.json
Labels: plugin_type: panel, plugin_update

#886 Update imageit to 1.0.2
  repo.json
Labels: plugin_type: panel, plugin_update

#838 Initial (re) release of new community scatter panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel

#813 Cloudflare Grafana App version 0.2.1
  repo.json
Labels: plugin_type: app, plugin_update

#889 Update DevOpsProdigy KubeGraf App version to 1.5.1
  repo.json
Labels: plugin_type: app, plugin_update

#890 updated grafanadependecy version
  repo.json
Labels: plugin_type: datasource, plugin_update

#844 Update Multistat to v1.7.0
  repo.json
Labels: plugin_type: panel, plugin_update

#836 Bump Annunciator panel plugin to v1.1.0
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#733 A panel that displays values as colored svg graphics.
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed

#900 Release v0.2.4 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#734 Add MapTrack3D panel plugin
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: feedback from author needed

#897 Update frser-sqlite-datasource to v1.0.1
  repo.json
Labels: plugin_type: datasource, plugin_update

#899 update graphql-datasource to v1.3.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#901 Update Kubegraf app version to 1.5.2
  repo.json
Labels: plugin_type: app, plugin_update

#905 Release Cognite datasource v2.2.0
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update
