Repository grafana/grafana-plugin-repository, pull requests merged in 2021-07, with the labels that each got.

#988 Bigquery grafana 2.0.2
  repo.json
Labels: submission/update, type/datasource

#980 Teamviewer Datasource v1.0.2
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/update, type/datasource

#985 Update tencentcloud-monitor-app to 2.2.0
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/update, type/app

#992 Anodot-panel v1.0.2
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/update, type/panel

#937 riemann datasource plugin 0.1.5
  repo.json
Labels: milestone/needs-changes, milestone/needs-review, submission/update, type/datasource

#972 Update pierosavi-imageit-panel to v1.0.4
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#973 Updated larona-epict-panel
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#977 Update VolkovLabs Image Panel 2.0.0
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#983 Update Redis Application 2.0.0
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/update, type/app

#948 Publish v2.3.0 of dalvany-image-panel
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, submission/update, type/panel

#959 New panel plugin to create "CDF" graphs
  repo.json
Labels: milestone/needs-changes, milestone/needs-review, submission/new, type/app

#984 Update Redis Explorer 2.0.0
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/update, type/app

#971 add simple-grpc-datasource plugin
  repo.json
Labels: milestone/needs-changes, milestone/needs-review, submission/new, type/datasource

#831 grafadruid-druid-datasource v1.2.0
  repo.json
Labels: milestone/needs-changes, milestone/needs-feedback, submission/new, type/datasource

#996 update innius-video-panel to v1.0.4
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, submission/update, type/panel

#930 Update williamvenner-timepickerbuttons-panel to 4.1.1
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#979 Upgrade Matomo Tracker panel to 0.2.3
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#1000 update auxmoney-waterfall-panel to 1.0.6
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, submission/update, type/panel

#978 Add Im comparison panel
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, submission/new, type/panel

#1003 Update tencentcloud-monitor-app to 2.2.1
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/update, type/app

#997 [Vertica]Bug fixes and query editor support
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, submission/update, type/datasource

#990 Support Grafana 8 for Pyroscope Panel Plugin
  repo.json
Labels: milestone/needs-metadata, submission/update, type/panel

#879 Update Chaos Mesh Data Source
  repo.json
Labels: milestone/needs-feedback, submission/update, type/datasource

#951 Add Pixie datasource plugin
  repo.json
Labels: milestone/needs-review, submission/new, type/datasource

#961 Lightstep Metrics Datasource
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/new, type/datasource

#1004 Anodot-datasource v.1.0.3.
  repo.json
Labels: milestone/needs-feedback, milestone/needs-review, signature/commercial, submission/update, type/datasource
