Repository grafana/grafana-plugin-repository, pull requests merged in 2021-06, with the labels that each got.

#960 Instana datasource plugin 3.3.0
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#903 Update Traceroute Map Panel to v0.3.0
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: feedback from author needed

#868 Release prometheus-alertmanager-datasource 1.0.0
  repo.json
Labels: plugin_type: datasource, plugin_update, pr_action: feedback from author needed

#923 Bump Multistat to v1.7.2
  repo.json
Labels: plugin_type: panel, plugin_update

#928 ClickHouse Database datasource plugin update to 2.3.1
  repo.json
Labels: plugin_type: datasource, plugin_update

#950 Release v0.2.5 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#925 Update macropower-analytics-panel to 2.0.0
  repo.json
Labels: submission/update, type/panel

#933 Update ae3e-plotly-panel to v0.4.0
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#967 Add Base64 Image/PDF panel 1.0.1
  repo.json
Labels: milestone/needs-review, submission/new, type/panel

#935 [Update] Streamr Datasource Plugin v1.5.0
  repo.json
Labels: milestone/needs-review, submission/update, type/datasource

#931 Added streaming support for vertica
  repo.json
Labels: milestone/needs-changes, submission/update, type/datasource

#963 Adds pyroscope panel and datasource plugins
  repo.json
Labels: milestone/needs-feedback, submission/new, type/datasource, type/panel

#975 Anodot Datasource 1.0.2
  repo.json
Labels: signature/commercial, submission/update, type/datasource

#965 Adds teamviewer datasource plugin
  repo.json
Labels: milestone/needs-review, signature/commercial, submission/new, type/datasource

#939 Update frser-sqlite-datasource to v2.0.0
  repo.json
Labels: milestone/needs-review, submission/update, type/datasource

#964 Adds Diagram v1.7.3
  repo.json
Labels: milestone/needs-review, submission/update, type/panel

#913 Update doitintl-bigquery-datasource to V2.0.2
  repo.json
Labels: submission/update, type/datasource

#920 ace svg version 0.0.10
  repo.json
Labels: milestone/needs-review, submission/update, type/panel
