Repository grafana/grafana-plugin-repository, pull requests merged in 2021-02, with the labels that each got.

#835 Update pierosavi-imageit-panel to v1
  repo.json
Labels: plugin_type: panel, plugin_update

#851 Update pierosavi-imageit-panel to v1.0.1
  repo.json
Labels: plugin_type: panel, plugin_update

#850 Instana datasource plugin 3.1.4
  repo.json
Labels: plugin_type: datasource, plugin_update

#759 Update ae3e-plotly-panel to v0.3.3
  repo.json
Labels: new_plugin, plugin_type: panel

#777 Add bilibala-echarts-panel
  repo.json
Labels: new_plugin, plugin_type: panel

#798 Woutervh mapbox panel 1.0.0
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: feedback from author needed

#856 Update Redis Data Source 1.3.1 to support streaming and Node Graph in Grafana 7.4
  repo.json
Labels: plugin_type: datasource, plugin_update

#860 Update Redis Application plug-in 1.1.0
  repo.json
Labels: plugin_type: app, plugin_update

#799 Adding thalysantana-appcenter-datasource v1.0.0
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed

#867 Update gapit-htmlgraphics-panel to v1.3.1
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: feedback from author needed

#662 Adding alert support for BigQuery plugin
  repo.json
Labels: angular, plugin_type: datasource, plugin_update, pr_action: changes needed

#873 Update clickhouse-grafana to 2.2.3
  repo.json
Labels: plugin_type: datasource, plugin_update
