Repository grafana/grafana-plugin-repository, pull requests merged in 2021-01, with the labels that each got.

#820 Update marcusolsson-csv-datasource to v0.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#822 Update marcusolsson-csv-datasource to 0.3.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#727 Add groonga-datasource 1.1.4
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed

#815 Humio: Add Version 3.2.0 and 3.2.1
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#816 gapit-htmlgraphics-panel update v1.2.0
  repo.json
Labels: plugin_type: panel, plugin_update

#803 ClickHouse Database datasource plugin update to 2.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#821 Update Redis Data Source 1.3.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#755 Add frser-sqlite-datasource
  repo.json
Labels: new_plugin, plugin_type: datasource

#804 Updated larona-epict-panel to v2.0.0
  repo.json
Labels: plugin_type: panel, plugin_update, pr_action: changes needed

#825 Update marcusolsson-dynamictext-panel
  repo.json
Labels: plugin_type: panel, plugin_update

#826 Update marcusolsson-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#828 Add marcusolsson-gantt-panel
  repo.json
Labels: new_plugin, plugin_type: panel

#823 Update frser-sqlite-datasource with v0.2.7
  repo.json
Labels: plugin_type: datasource, plugin_update

#829 Instana datasource plugin 3.1.3
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#742 Add Meteostat Datasource
  repo.json
Labels: new_plugin, plugin_type: datasource, pr_action: changes needed

#763 Add perfcurve-panel v1.3.0
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: feedback from author needed

#814 Update KubeGraf version to v1.5.0
  repo.json
Labels: plugin_type: app, plugin_update

#779 Update fifemon-graphql-datasource to v1.2.0
  repo.json
Labels: plugin_type: datasource, plugin_update

#837 Release v0.2.3 simpod-json-datasource
  repo.json
Labels: plugin_type: datasource, plugin_update

#846 Humio version 3.2.3
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#843 riemann datasource plugin 0.1.4
  repo.json
Labels: plugin_type: datasource, plugin_update
