Repository grafana/grafana-plugin-repository, pull requests merged in 2021-04, with the labels that each got.

#907 Add TencentCloud Monitor Grafana App Plugin
  repo.json
Labels: commercial plugin, new_plugin, plugin_type: app

#885 Add anodot-panel plugin
  repo.json
Labels: commercial plugin, new_plugin, plugin_type: datasource, plugin_type: panel, pr_action: feedback from author needed

#918 Update tencentcloud-monitor-app to 2.0.2
  repo.json
Labels: commercial plugin, plugin_type: app, plugin_type: datasource, plugin_update

#869 Adding a vertica data source plugin
  repo.json
Labels: new_plugin, plugin_type: datasource

#878 Update 'pr0ps-trackmap-panel' to v2.1.2
  repo.json
Labels: plugin_type: panel, plugin_update

#924 adds diagram 1.7.2
  repo.json
Labels: plugin_type: panel, plugin_update

#911 humio 3.2.4
  repo.json
Labels: commercial plugin, plugin_type: datasource, plugin_update

#863 add auxmoney-waterfall-panel 1.0.3
  repo.json
Labels: new_plugin, plugin_type: panel, pr_action: changes needed
