Repository grafana/grafana-plugin-repository, pull requests merged in 2021-09, with the labels that each got.

#1006 Release v0.2.6 simpod-json-datasource
  repo.json
Labels: type/datasource, milestone/needs-review, submission/update

#787 Update Service Dependency Graph Plugin
  repo.json
Labels: milestone/needs-feedback, type/panel, milestone/needs-review, submission/update

#1002 upgrade video-panel-plugion to v1.0.5
  repo.json
Labels: type/panel, milestone/needs-review, submission/update

#1038 Update VolkovLabs Image Panel 2.1.1
  repo.json
Labels: type/panel, milestone/needs-review, submission/update

#1039 ace svg version 0.0.11
  repo.json
Labels: type/panel, milestone/needs-review, submission/update

#1029 Update ae3e-plotly-panel to v0.5.0
  repo.json
Labels: type/panel, milestone/needs-review, submission/update
